# Generated by Django 4.0.5 on 2022-06-25 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analyze_txt', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TextInputs',
            new_name='TextInput',
        ),
    ]
