# Generated by Django 4.0.5 on 2022-07-02 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyze_txt', '0003_alter_textinput_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='textinput',
            name='title',
            field=models.CharField(default='No title', max_length=2000),
            preserve_default=False,
        ),
    ]
