# Generated by Django 4.0.5 on 2022-07-05 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyze_txt', '0005_alter_textinput_case_sensitive'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataProviderModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.TextField()),
            ],
        ),
    ]
