# Generated by Django 4.0.5 on 2022-07-05 23:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analyze_txt', '0006_dataprovidermodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DataProviderModel',
        ),
    ]
